import { GoogleGenAI, Type } from "@google/genai";
import type { ExtractedContent, LlmVerdict } from "./types";

const MODEL = process.env.GEMINI_MODEL ?? "gemini-2.5-flash";
const MAX_INPUT_WORDS = 3000;

export function llmAvailable(): boolean {
  return Boolean(process.env.GEMINI_API_KEY);
}

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    aiProbability: {
      type: Type.NUMBER,
      description: "Probability 0-100 that the text is AI-generated.",
    },
    signals: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          name: { type: Type.STRING },
          description: { type: Type.STRING },
        },
        required: ["name", "description"],
      },
    },
    reasoning: { type: Type.STRING },
  },
  required: ["aiProbability", "signals", "reasoning"],
};

export async function analyzeWithLlm(content: ExtractedContent): Promise<LlmVerdict> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  const words = content.textContent.split(/\s+/);
  const sample =
    words.length > MAX_INPUT_WORDS ? words.slice(0, MAX_INPUT_WORDS).join(" ") + " …" : content.textContent;

  const hasScreenshot = Boolean(content.screenshot);
  const thinText = content.wordCount < 100;

  const prompt = `You are an expert at detecting AI-generated websites and content.

Analyze the page at ${content.url} and estimate the probability (0-100) that it was generated by AI (a large language model or an AI website builder) rather than made by a human.

For the TEXT consider: perplexity and burstiness (humans vary sentence rhythm and make idiosyncratic choices), stock LLM phrasing, hedging and over-qualification, surface-level breadth with no first-hand detail, formulaic structure, absence of personal anecdotes or genuine opinion, and generic transitions.
${
  hasScreenshot
    ? `
A screenshot of the rendered page is attached.

IMPORTANT CALIBRATION: polish, clean typography, and a professional layout are NOT evidence of human authorship. AI builders (Lovable, v0, Bolt, Google AI Studio) produce polished shadcn/Tailwind-style templates by default, so a slick modern site should raise your suspicion, not lower it.

AI-leaning visual tells: the shadcn/Tailwind template aesthetic (uniform rounded cards, icon + title + blurb grids with lucide-style icons, gradient or glassmorphism heroes, perfectly uniform section rhythm), generic marketing copy with em dashes, stock or AI-generated imagery, and branding with no history or specificity.

Human-leaning visual tells: signs of age and iteration (inconsistent styles, legacy widgets, dated design choices), real photographs of real people and places, dense idiosyncratic content, and small imperfections or typos.
${thinText ? "The page has very little text, so base your judgment primarily on the screenshot." : ""}`
    : ""
}
Do NOT penalize professional editing, translated text, or non-native English on their own.
${
  content.headHtml
    ? `
The RAW HTML HEAD below is exactly as the server sent it. Weigh it as forensic evidence:
- HUMAN-leaning: hand-edit artifacts such as commented-out tags, inconsistent attribute quoting (' vs "), informal developer comments (<!-- SEO -->), nonstandard attribute values, custom self-hosted asset domains. One-shot AI exports and AI builders emit uniform, pristine markup, so genuine hand-edit mess is strong human evidence and outweighs a generic-looking visual design.
- AI-leaning: builder boilerplate, template comments, or a bare auto-generated shell.

RAW HTML HEAD:
${content.headHtml}
`
    : ""
}
TITLE: ${content.title}

HEADINGS:
${content.headings.slice(0, 20).join("\n") || "(none)"}

BODY TEXT:
${sample || "(almost none)"}`;

  const parts: ({ text: string } | { inlineData: { mimeType: string; data: string } })[] = [
    { text: prompt },
  ];
  if (content.screenshot) {
    parts.push({ inlineData: { mimeType: "image/jpeg", data: content.screenshot } });
  }

  const response = await ai.models.generateContent({
    model: MODEL,
    contents: parts,
    config: {
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
      temperature: 0.2,
    },
  });

  const parsed = JSON.parse(response.text ?? "{}") as LlmVerdict;
  return {
    aiProbability: Math.max(0, Math.min(100, Number(parsed.aiProbability) || 0)),
    signals: Array.isArray(parsed.signals) ? parsed.signals.slice(0, 10) : [],
    reasoning: typeof parsed.reasoning === "string" ? parsed.reasoning : "",
  };
}
